name: critterpedia_plus
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  copy_with_extension: ^5.0.1
  dio: ^5.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  get_it: ^7.2.0
  http: ^0.13.5
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  typed_result: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.1
  injectable_generator:

flutter:
  uses-material-design: true
